/* =====================================================================
   IVOL Warehouse Junior — teksten in 4 talen (nl, en, es, el)
   Picqer-menunamen blijven Nederlands (zo staan ze in Picqer).
   "a|b" = enkelvoud|meervoud, {n} {x} = invullen.
   ===================================================================== */
window.JT = {
nl:{
  loc:'nl-NL', naam:'Nederlands',
  'nav.vandaag':'Vandaag', 'nav.aanvullen':'Aanvullen', 'nav.containers':'Containers', 'nav.labels':'Palletlabels',
  'sync.laden':'laden…', 'sync.ok':'verbonden', 'sync.fout':'geen verbinding', vernieuw:'Vernieuwen',
  week:'Week {n}',
  lijstVan:'Backorders: {b} · Aanvuladvies: {a}',
  oud:'De lijst is niet van vandaag. Vernieuw hem eerst.', oudKnop:'Lijst vernieuwen →',
  'tegel.nu':'Nu verplaatsen', ordersWacht:'{n} order wacht|{n} orders wachten',
  'tegel.ronde':'Aanvulronde', 'tegel.rondeSub':'open, per gang',
  'tegel.cont':'Containers', volgende:'Volgende: {x}', geenGepland:'geen gepland',
  'tegel.labels':'Palletlabels', 'tegel.labelsSub':'labels maken en printen',
  uitlegTitel:'Zo werkt aanvullen',
  uitleg:[
    '<b>Lijst vernieuwen</b> (elke ochtend en na elke ronde): maak in Picqer deze twee exports en sleep ze in het vak <i>Lijst vernieuwen</i>. De lijst wordt dan voor iedereen bijgewerkt.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Nu verplaatsen</b> eerst. Hier wachten klantorders op. De oudste order staat bovenaan. Pak het aantal uit de bulklocatie (links) en zet het op de picklocatie (rechts).',
    'Staat er <b>geen specifieke locatie</b>? Dan heeft het product geen picklocatie: verplaats het in Picqer naar geen specifieke locatie.',
    'Verwerk elke verplaatsing ook in Picqer (van bulk naar pick) en tik hier het vakje aan ✓. Iedereen ziet dan dat het gedaan is.',
    'Alles van Nu verplaatsen gedaan? Picqer → Backorders → <b>Verwerk backorders</b>. De orders worden dan picklijsten.',
    'Daarna de <b>Aanvulronde</b>: per gang de picklocaties aanvullen met het aantal van het advies. Ook in Picqer verwerken en afvinken.',
    'Klopt er iets niet (bulk leeg, ander aantal, verkeerde plek)? Meld het bij Daan.'
  ],
  vernieuwTitel:'Lijst vernieuwen',
  dropTekst:'Sleep de backorder-export (Excel) en het aanvuladvies (PDF) hierin, of tik om te kiezen',
  bezig:'Bezig: {x}…', okBo:'✓ Backorders: {n} orders', okAdv:'✓ Aanvuladvies: {n} regels',
  nietNodig:'✗ {x}: dit bestand is hier niet nodig. Alleen backorders (Excel) en aanvuladvies (PDF).',
  bijgewerkt:'Lijst bijgewerkt',
  open:'{n} open', print:'Print', gang:'Gang', alle:'alle', sinds:'sinds {x}',
  orders:'{n} order|{n} orders', pickvrd:'pickvoorraad {n}', pqAdv:'advies Picqer {n}',
  voorOrders:'voor orders', advies:'advies',
  geenLoc:'geen specifieke locatie', ofNieuw:'of nieuw:', bulkOnb:'bulk onbekend', geenPick:'geen picklocatie',
  retourkar:'op retourkar {x}', wachtVst:'wacht op VST: verplaatsen maakt nog geen order compleet',
  leegNu:'Niets te verplaatsen voor orders.', leegRonde:'Geen aanvulronde. Vernieuw de lijst met een nieuw aanvuladvies.',
  klaarNu:'Alles verplaatst en in Picqer verwerkt? Dan: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Klantorders wachten op deze producten. Oudste order bovenaan. Van bulk (links) naar pick (rechts).',
  introRonde:'Rest van het aanvuladvies, per gang in looprichting. Vul de picklocatie aan met het aantal van het advies.',
  openVan:'{a} open van {b}', nietIngeladen:'nog niet ingeladen', vandaagOm:'vandaag {x}',
  contIntro:'Containers die eraan komen. De losplanning (PDF) verschijnt zodra Daan alles heeft ingevuld.',
  eta:'ETA (schatting)', lossen:'Lossen', geenDatum:'nog geen datum',
  pakbon:'Pakbon', losplanning:'Losplanning (PDF)', losplanningVolgt:'Losplanning volgt', gemaakt:'gemaakt {x}',
  geenCont:'Geen containers gepland.',
  'st.concept':'in voorbereiding', 'st.ingepland':'ingepland', 'st.gelost':'gelost',
  vandaag:'vandaag', morgen:'morgen',
  openMislukt:'Openen lukt niet: {x}', bestandLaden:'Bestand laden…',
  geenVerb:'Geen verbinding met de database', geenVerbTekst:'Probeer het over een paar minuten opnieuw. Blijft het zo? Meld het bij Daan.',
  opgeslagen:'Opgeslagen', misScherm:'Er ging iets mis op dit scherm'
},
en:{
  loc:'en-GB', naam:'English',
  'nav.vandaag':'Today', 'nav.aanvullen':'Replenish', 'nav.containers':'Containers', 'nav.labels':'Pallet labels',
  'sync.laden':'loading…', 'sync.ok':'connected', 'sync.fout':'no connection', vernieuw:'Refresh',
  week:'Week {n}',
  lijstVan:'Backorders: {b} · Replenishment advice: {a}',
  oud:'The list is not from today. Refresh it first.', oudKnop:'Refresh list →',
  'tegel.nu':'Move now', ordersWacht:'{n} order waiting|{n} orders waiting',
  'tegel.ronde':'Replenishment round', 'tegel.rondeSub':'open, by aisle',
  'tegel.cont':'Containers', volgende:'Next: {x}', geenGepland:'none planned',
  'tegel.labels':'Pallet labels', 'tegel.labelsSub':'make and print labels',
  uitlegTitel:'How replenishing works',
  uitleg:[
    '<b>Refresh the list</b> (every morning and after each round): make these two exports in Picqer and drop them in the box <i>Refresh list</i>. The list then updates for everyone.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Move now</b> first. Customer orders are waiting for these. The oldest order is at the top. Take the quantity from the bulk location (left) and put it on the pick location (right).',
    'Does it say <b>no specific location</b>? Then the product has no pick location: in Picqer, move it to "geen specifieke locatie".',
    'Also process every move in Picqer (from bulk to pick) and tap the box here ✓. Everyone then sees it is done.',
    'Everything in Move now done? Picqer → Backorders → <b>Verwerk backorders</b> (process backorders). The orders then become picklists.',
    'Then the <b>Replenishment round</b>: per aisle, top up the pick locations with the advised quantity. Also process it in Picqer and tick it off.',
    'Something wrong (bulk empty, different quantity, wrong place)? Tell Daan.'
  ],
  vernieuwTitel:'Refresh list',
  dropTekst:'Drop the backorder export (Excel) and the replenishment advice (PDF) here, or tap to choose',
  bezig:'Working: {x}…', okBo:'✓ Backorders: {n} orders', okAdv:'✓ Replenishment advice: {n} lines',
  nietNodig:'✗ {x}: this file is not needed here. Only backorders (Excel) and replenishment advice (PDF).',
  bijgewerkt:'List updated',
  open:'{n} open', print:'Print', gang:'Aisle', alle:'all', sinds:'since {x}',
  orders:'{n} order|{n} orders', pickvrd:'pick stock {n}', pqAdv:'Picqer advice {n}',
  voorOrders:'for orders', advies:'advice',
  geenLoc:'no specific location', ofNieuw:'or new:', bulkOnb:'bulk unknown', geenPick:'no pick location',
  retourkar:'on return cart {x}', wachtVst:'waiting for VST: moving does not complete an order yet',
  leegNu:'Nothing to move for orders.', leegRonde:'No replenishment round. Refresh the list with a new replenishment advice.',
  klaarNu:'All moved and processed in Picqer? Then: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Customer orders are waiting for these products. Oldest order at the top. From bulk (left) to pick (right).',
  introRonde:'Rest of the replenishment advice, per aisle in walking order. Top up the pick location with the advised quantity.',
  openVan:'{a} open of {b}', nietIngeladen:'not loaded yet', vandaagOm:'today {x}',
  contIntro:'Containers on their way. The unloading plan (PDF) appears as soon as Daan has filled everything in.',
  eta:'ETA (estimate)', lossen:'Unloading', geenDatum:'no date yet',
  pakbon:'Packing list', losplanning:'Unloading plan (PDF)', losplanningVolgt:'Unloading plan to follow', gemaakt:'made {x}',
  geenCont:'No containers planned.',
  'st.concept':'being prepared', 'st.ingepland':'scheduled', 'st.gelost':'unloaded',
  vandaag:'today', morgen:'tomorrow',
  openMislukt:'Could not open: {x}', bestandLaden:'Loading file…',
  geenVerb:'No connection to the database', geenVerbTekst:'Try again in a few minutes. Still not working? Tell Daan.',
  opgeslagen:'Saved', misScherm:'Something went wrong on this screen'
},
es:{
  loc:'es-ES', naam:'Español',
  'nav.vandaag':'Hoy', 'nav.aanvullen':'Reponer', 'nav.containers':'Contenedores', 'nav.labels':'Etiquetas de palé',
  'sync.laden':'cargando…', 'sync.ok':'conectado', 'sync.fout':'sin conexión', vernieuw:'Actualizar',
  week:'Semana {n}',
  lijstVan:'Backorders: {b} · Consejo de reposición: {a}',
  oud:'La lista no es de hoy. Actualízala primero.', oudKnop:'Actualizar lista →',
  'tegel.nu':'Mover ahora', ordersWacht:'{n} pedido esperando|{n} pedidos esperando',
  'tegel.ronde':'Ronda de reposición', 'tegel.rondeSub':'pendientes, por pasillo',
  'tegel.cont':'Contenedores', volgende:'Siguiente: {x}', geenGepland:'ninguno previsto',
  'tegel.labels':'Etiquetas de palé', 'tegel.labelsSub':'crear e imprimir etiquetas',
  uitlegTitel:'Cómo funciona la reposición',
  uitleg:[
    '<b>Actualizar la lista</b> (cada mañana y después de cada ronda): haz estas dos exportaciones en Picqer y arrástralas a la casilla <i>Actualizar lista</i>. La lista se actualiza para todos.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Mover ahora</b> primero. Aquí esperan pedidos de clientes. El pedido más antiguo está arriba. Coge la cantidad de la ubicación bulk (izquierda) y ponla en la ubicación pick (derecha).',
    '¿Pone <b>sin ubicación específica</b>? Entonces el producto no tiene ubicación pick: en Picqer, muévelo a "geen specifieke locatie".',
    'Registra también cada movimiento en Picqer (de bulk a pick) y marca aquí la casilla ✓. Así todos ven que está hecho.',
    '¿Todo lo de Mover ahora hecho? Picqer → Backorders → <b>Verwerk backorders</b> (procesar backorders). Los pedidos pasan a ser listas de picking.',
    'Después la <b>Ronda de reposición</b>: por pasillo, repón las ubicaciones pick con la cantidad del consejo. Regístralo también en Picqer y márcalo.',
    '¿Algo no cuadra (bulk vacío, otra cantidad, sitio equivocado)? Díselo a Daan.'
  ],
  vernieuwTitel:'Actualizar lista',
  dropTekst:'Arrastra aquí la exportación de backorders (Excel) y el consejo de reposición (PDF), o toca para elegir',
  bezig:'Procesando: {x}…', okBo:'✓ Backorders: {n} pedidos', okAdv:'✓ Consejo de reposición: {n} líneas',
  nietNodig:'✗ {x}: este archivo no hace falta aquí. Solo backorders (Excel) y consejo de reposición (PDF).',
  bijgewerkt:'Lista actualizada',
  open:'{n} pendientes', print:'Imprimir', gang:'Pasillo', alle:'todos', sinds:'desde {x}',
  orders:'{n} pedido|{n} pedidos', pickvrd:'stock en pick {n}', pqAdv:'consejo Picqer {n}',
  voorOrders:'para pedidos', advies:'consejo',
  geenLoc:'sin ubicación específica', ofNieuw:'o nueva:', bulkOnb:'bulk desconocido', geenPick:'sin ubicación pick',
  retourkar:'en carro de devoluciones {x}', wachtVst:'espera a VST: mover aún no completa ningún pedido',
  leegNu:'Nada que mover para pedidos.', leegRonde:'No hay ronda de reposición. Actualiza la lista con un nuevo consejo de reposición.',
  klaarNu:'¿Todo movido y registrado en Picqer? Entonces: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Hay pedidos de clientes esperando estos productos. El más antiguo arriba. De bulk (izquierda) a pick (derecha).',
  introRonde:'Resto del consejo de reposición, por pasillo en orden de recorrido. Repón la ubicación pick con la cantidad del consejo.',
  openVan:'{a} pendientes de {b}', nietIngeladen:'aún no cargado', vandaagOm:'hoy {x}',
  contIntro:'Contenedores que están por llegar. El plan de descarga (PDF) aparece en cuanto Daan lo haya completado todo.',
  eta:'ETA (estimada)', lossen:'Descarga', geenDatum:'aún sin fecha',
  pakbon:'Albarán', losplanning:'Plan de descarga (PDF)', losplanningVolgt:'Plan de descarga pendiente', gemaakt:'creado {x}',
  geenCont:'No hay contenedores previstos.',
  'st.concept':'en preparación', 'st.ingepland':'programado', 'st.gelost':'descargado',
  vandaag:'hoy', morgen:'mañana',
  openMislukt:'No se pudo abrir: {x}', bestandLaden:'Cargando archivo…',
  geenVerb:'Sin conexión con la base de datos', geenVerbTekst:'Vuelve a intentarlo en unos minutos. ¿Sigue igual? Díselo a Daan.',
  opgeslagen:'Guardado', misScherm:'Algo salió mal en esta pantalla'
},
el:{
  loc:'el-GR', naam:'Ελληνικά',
  'nav.vandaag':'Σήμερα', 'nav.aanvullen':'Αναπλήρωση', 'nav.containers':'Κοντέινερ', 'nav.labels':'Ετικέτες παλετών',
  'sync.laden':'φόρτωση…', 'sync.ok':'συνδέθηκε', 'sync.fout':'χωρίς σύνδεση', vernieuw:'Ανανέωση',
  week:'Εβδομάδα {n}',
  lijstVan:'Backorders: {b} · Πρόταση αναπλήρωσης: {a}',
  oud:'Η λίστα δεν είναι σημερινή. Ανανέωσέ την πρώτα.', oudKnop:'Ανανέωση λίστας →',
  'tegel.nu':'Μετακίνηση τώρα', ordersWacht:'{n} παραγγελία περιμένει|{n} παραγγελίες περιμένουν',
  'tegel.ronde':'Γύρος αναπλήρωσης', 'tegel.rondeSub':'ανοιχτά, ανά διάδρομο',
  'tegel.cont':'Κοντέινερ', volgende:'Επόμενο: {x}', geenGepland:'κανένα προγραμματισμένο',
  'tegel.labels':'Ετικέτες παλετών', 'tegel.labelsSub':'δημιουργία και εκτύπωση ετικετών',
  uitlegTitel:'Πώς γίνεται η αναπλήρωση',
  uitleg:[
    '<b>Ανανέωση λίστας</b> (κάθε πρωί και μετά από κάθε γύρο): κάνε αυτές τις δύο εξαγωγές στο Picqer και σύρε τις στο πλαίσιο <i>Ανανέωση λίστας</i>. Η λίστα ενημερώνεται για όλους.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Μετακίνηση τώρα</b> πρώτα. Εδώ περιμένουν παραγγελίες πελατών. Η παλαιότερη παραγγελία είναι πάνω. Πάρε την ποσότητα από τη θέση bulk (αριστερά) και βάλ’ την στη θέση pick (δεξιά).',
    'Γράφει <b>χωρίς συγκεκριμένη θέση</b>; Τότε το προϊόν δεν έχει θέση pick: στο Picqer μετακίνησέ το σε «geen specifieke locatie».',
    'Κατάγραψε κάθε μετακίνηση και στο Picqer (από bulk σε pick) και πάτησε εδώ το κουτάκι ✓. Έτσι όλοι βλέπουν ότι έγινε.',
    'Έγιναν όλα στο «Μετακίνηση τώρα»; Picqer → Backorders → <b>Verwerk backorders</b> (επεξεργασία backorders). Οι παραγγελίες γίνονται λίστες συλλογής.',
    'Μετά ο <b>Γύρος αναπλήρωσης</b>: ανά διάδρομο, συμπλήρωσε τις θέσεις pick με την προτεινόμενη ποσότητα. Κατάγραψέ το και στο Picqer και σημείωσέ το.',
    'Κάτι δεν ταιριάζει (άδειο bulk, άλλη ποσότητα, λάθος θέση); Πες το στον Daan.'
  ],
  vernieuwTitel:'Ανανέωση λίστας',
  dropTekst:'Σύρε εδώ την εξαγωγή backorders (Excel) και την πρόταση αναπλήρωσης (PDF), ή πάτησε για επιλογή',
  bezig:'Επεξεργασία: {x}…', okBo:'✓ Backorders: {n} παραγγελίες', okAdv:'✓ Πρόταση αναπλήρωσης: {n} γραμμές',
  nietNodig:'✗ {x}: αυτό το αρχείο δεν χρειάζεται εδώ. Μόνο backorders (Excel) και πρόταση αναπλήρωσης (PDF).',
  bijgewerkt:'Η λίστα ενημερώθηκε',
  open:'{n} ανοιχτά', print:'Εκτύπωση', gang:'Διάδρομος', alle:'όλοι', sinds:'από {x}',
  orders:'{n} παραγγελία|{n} παραγγελίες', pickvrd:'απόθεμα pick {n}', pqAdv:'πρόταση Picqer {n}',
  voorOrders:'για παραγγελίες', advies:'πρόταση',
  geenLoc:'χωρίς συγκεκριμένη θέση', ofNieuw:'ή νέα:', bulkOnb:'άγνωστο bulk', geenPick:'χωρίς θέση pick',
  retourkar:'σε καρότσι επιστροφών {x}', wachtVst:'περιμένει VST: η μετακίνηση δεν ολοκληρώνει ακόμα παραγγελία',
  leegNu:'Τίποτα για μετακίνηση για παραγγελίες.', leegRonde:'Δεν υπάρχει γύρος αναπλήρωσης. Ανανέωσε τη λίστα με νέα πρόταση αναπλήρωσης.',
  klaarNu:'Όλα μετακινήθηκαν και καταγράφηκαν στο Picqer; Τότε: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Παραγγελίες πελατών περιμένουν αυτά τα προϊόντα. Η παλαιότερη πάνω. Από bulk (αριστερά) σε pick (δεξιά).',
  introRonde:'Υπόλοιπο της πρότασης αναπλήρωσης, ανά διάδρομο με σειρά διαδρομής. Συμπλήρωσε τη θέση pick με την προτεινόμενη ποσότητα.',
  openVan:'{a} ανοιχτά από {b}', nietIngeladen:'δεν έχει φορτωθεί ακόμα', vandaagOm:'σήμερα {x}',
  contIntro:'Κοντέινερ που έρχονται. Το πλάνο εκφόρτωσης (PDF) εμφανίζεται μόλις ο Daan συμπληρώσει τα πάντα.',
  eta:'ETA (εκτίμηση)', lossen:'Εκφόρτωση', geenDatum:'χωρίς ημερομηνία ακόμα',
  pakbon:'Δελτίο αποστολής', losplanning:'Πλάνο εκφόρτωσης (PDF)', losplanningVolgt:'Το πλάνο εκφόρτωσης ακολουθεί', gemaakt:'δημιουργήθηκε {x}',
  geenCont:'Δεν υπάρχουν προγραμματισμένα κοντέινερ.',
  'st.concept':'σε προετοιμασία', 'st.ingepland':'προγραμματισμένο', 'st.gelost':'ξεφορτώθηκε',
  vandaag:'σήμερα', morgen:'αύριο',
  openMislukt:'Δεν άνοιξε: {x}', bestandLaden:'Φόρτωση αρχείου…',
  geenVerb:'Χωρίς σύνδεση με τη βάση δεδομένων', geenVerbTekst:'Δοκίμασε ξανά σε λίγα λεπτά. Αν συνεχίζει, πες το στον Daan.',
  opgeslagen:'Αποθηκεύτηκε', misScherm:'Κάτι πήγε στραβά σε αυτή την οθόνη'
}
};
