/* =====================================================================
   IVOL Warehouse Junior — teksten in 4 talen (nl, en, es, el)
   Picqer-menunamen blijven Nederlands (zo staan ze in Picqer).
   "a|b" = enkelvoud|meervoud, {n} {x} = invullen.
   ===================================================================== */
window.JT = {
nl:{
  loc:'nl-NL', naam:'Nederlands',
  'nav.vandaag':'Vandaag', 'nav.aanvullen':'Aanvullen', 'nav.containers':'Containers', 'nav.labels':'Palletlabels',
  'sync.laden':'laden…', 'sync.ok':'verbonden', 'sync.fout':'geen verbinding', vernieuw:'Vernieuwen',
  week:'Week {n}',
  lijstVan:'Backorders: {b} · Aanvuladvies: {a}',
  oud:'De lijst is niet van vandaag. Vernieuw hem eerst.', oudKnop:'Lijst vernieuwen →',
  'tegel.nu':'Nu verplaatsen', ordersWacht:'{n} order wacht|{n} orders wachten',
  'tegel.ronde':'Aanvulronde', 'tegel.rondeSub':'open, per gang',
  'tegel.cont':'Containers', volgende:'Volgende: {x}', geenGepland:'geen gepland',
  'tegel.labels':'Palletlabels', 'tegel.labelsSub':'labels maken en printen',
  uitlegTitel:'Zo werkt aanvullen',
  uitleg:[
    '<b>Lijst vernieuwen</b> (elke ochtend en na elke ronde): maak in Picqer deze twee exports en sleep ze in het vak <i>Lijst vernieuwen</i>. De lijst wordt dan voor iedereen bijgewerkt.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Nu verplaatsen</b> eerst. Hier wachten klantorders op. De oudste order staat bovenaan. Pak het aantal uit de bulklocatie (links) en zet het op de picklocatie (rechts).',
    'Staat er <b>geen specifieke locatie</b>? Dan heeft het product geen picklocatie: verplaats het in Picqer naar geen specifieke locatie.',
    'Verwerk elke verplaatsing ook in Picqer (van bulk naar pick) en tik hier het vakje aan ✓. Iedereen ziet dan dat het gedaan is.',
    'Alles van Nu verplaatsen gedaan? Picqer → Backorders → <b>Verwerk backorders</b>. De orders worden dan picklijsten.',
    'Daarna de <b>Aanvulronde</b>: per gang de picklocaties aanvullen met het aantal van het advies. Ook in Picqer verwerken en afvinken.',
    'Klopt er iets niet (bulk leeg, ander aantal, verkeerde plek)? Meld het bij Daan.'
  ],
  vernieuwTitel:'Lijst vernieuwen',
  dropTekst:'Sleep de backorder-export (Excel) en het aanvuladvies (PDF) hierin, of tik om te kiezen',
  bezig:'Bezig: {x}…', okBo:'✓ Backorders: {n} orders', okAdv:'✓ Aanvuladvies: {n} regels',
  nietNodig:'✗ {x}: dit bestand is hier niet nodig. Alleen backorders (Excel) en aanvuladvies (PDF).',
  bijgewerkt:'Lijst bijgewerkt',
  open:'{n} open', print:'Print', gang:'Gang', alle:'alle', sinds:'sinds {x}',
  orders:'{n} order|{n} orders', pickvrd:'pickvoorraad {n}', pqAdv:'advies Picqer {n}',
  voorOrders:'voor orders', advies:'advies',
  geenLoc:'geen specifieke locatie', ofNieuw:'of nieuw:', bulkOnb:'bulk onbekend', geenPick:'geen picklocatie',
  retourkar:'op retourkar {x}', wachtVst:'wacht op VST: verplaatsen maakt nog geen order compleet',
  leegNu:'Niets te verplaatsen voor orders.', leegRonde:'Geen aanvulronde. Vernieuw de lijst met een nieuw aanvuladvies.',
  klaarNu:'Alles verplaatst en in Picqer verwerkt? Dan: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Klantorders wachten op deze producten. Oudste order bovenaan. Van bulk (links) naar pick (rechts).',
  introRonde:'Rest van het aanvuladvies, per gang in looprichting. Vul de picklocatie aan met het aantal van het advies.',
  openVan:'{a} open van {b}', nietIngeladen:'nog niet ingeladen', vandaagOm:'vandaag {x}',
  contIntro:'Containers die eraan komen. De losplanning (PDF) verschijnt zodra Daan alles heeft ingevuld.',
  eta:'ETA (schatting)', lossen:'Lossen', geenDatum:'nog geen datum',
  pakbon:'Pakbon', losplanning:'Losplanning (PDF)', losplanningVolgt:'Losplanning volgt', gemaakt:'gemaakt {x}',
  geenCont:'Geen containers gepland.',
  'st.concept':'in voorbereiding', 'st.ingepland':'ingepland', 'st.gelost':'gelost',
  vandaag:'vandaag', morgen:'morgen',
  openMislukt:'Openen lukt niet: {x}', bestandLaden:'Bestand laden…',
  geenVerb:'Geen verbinding met de database', geenVerbTekst:'Probeer het over een paar minuten opnieuw. Blijft het zo? Meld het bij Daan.',
  opgeslagen:'Opgeslagen', misScherm:'Er ging iets mis op dit scherm'
},
en:{
  loc:'en-GB', naam:'English',
  'nav.vandaag':'Today', 'nav.aanvullen':'Replenish', 'nav.containers':'Containers', 'nav.labels':'Pallet labels',
  'sync.laden':'loading…', 'sync.ok':'connected', 'sync.fout':'no connection', vernieuw:'Refresh',
  week:'Week {n}',
  lijstVan:'Backorders: {b} · Replenishment advice: {a}',
  oud:'The list is not from today. Refresh it first.', oudKnop:'Refresh list →',
  'tegel.nu':'Move now', ordersWacht:'{n} order waiting|{n} orders waiting',
  'tegel.ronde':'Replenishment round', 'tegel.rondeSub':'open, by aisle',
  'tegel.cont':'Containers', volgende:'Next: {x}', geenGepland:'none planned',
  'tegel.labels':'Pallet labels', 'tegel.labelsSub':'make and print labels',
  uitlegTitel:'How replenishing works',
  uitleg:[
    '<b>Refresh the list</b> (every morning and after each round): make these two exports in Picqer and drop them in the box <i>Refresh list</i>. The list then updates for everyone.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Move now</b> first. Customer orders are waiting for these. The oldest order is at the top. Take the quantity from the bulk location (left) and put it on the pick location (right).',
    'Does it say <b>no specific location</b>? Then the product has no pick location: in Picqer, move it to "geen specifieke locatie".',
    'Also process every move in Picqer (from bulk to pick) and tap the box here ✓. Everyone then sees it is done.',
    'Everything in Move now done? Picqer → Backorders → <b>Verwerk backorders</b> (process backorders). The orders then become picklists.',
    'Then the <b>Replenishment round</b>: per aisle, top up the pick locations with the advised quantity. Also process it in Picqer and tick it off.',
    'Something wrong (bulk empty, different quantity, wrong place)? Tell Daan.'
  ],
  vernieuwTitel:'Refresh list',
  dropTekst:'Drop the backorder export (Excel) and the replenishment advice (PDF) here, or tap to choose',
  bezig:'Working: {x}…', okBo:'✓ Backorders: {n} orders', okAdv:'✓ Replenishment advice: {n} lines',
  nietNodig:'✗ {x}: this file is not needed here. Only backorders (Excel) and replenishment advice (PDF).',
  bijgewerkt:'List updated',
  open:'{n} open', print:'Print', gang:'Aisle', alle:'all', sinds:'since {x}',
  orders:'{n} order|{n} orders', pickvrd:'pick stock {n}', pqAdv:'Picqer advice {n}',
  voorOrders:'for orders', advies:'advice',
  geenLoc:'no specific location', ofNieuw:'or new:', bulkOnb:'bulk unknown', geenPick:'no pick location',
  retourkar:'on return cart {x}', wachtVst:'waiting for VST: moving does not complete an order yet',
  leegNu:'Nothing to move for orders.', leegRonde:'No replenishment round. Refresh the list with a new replenishment advice.',
  klaarNu:'All moved and processed in Picqer? Then: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Customer orders are waiting for these products. Oldest order at the top. From bulk (left) to pick (right).',
  introRonde:'Rest of the replenishment advice, per aisle in walking order. Top up the pick location with the advised quantity.',
  openVan:'{a} open of {b}', nietIngeladen:'not loaded yet', vandaagOm:'today {x}',
  contIntro:'Containers on their way. The unloading plan (PDF) appears as soon as Daan has filled everything in.',
  eta:'ETA (estimate)', lossen:'Unloading', geenDatum:'no date yet',
  pakbon:'Packing list', losplanning:'Unloading plan (PDF)', losplanningVolgt:'Unloading plan to follow', gemaakt:'made {x}',
  geenCont:'No containers planned.',
  'st.concept':'being prepared', 'st.ingepland':'scheduled', 'st.gelost':'unloaded',
  vandaag:'today', morgen:'tomorrow',
  openMislukt:'Could not open: {x}', bestandLaden:'Loading file…',
  geenVerb:'No connection to the database', geenVerbTekst:'Try again in a few minutes. Still not working? Tell Daan.',
  opgeslagen:'Saved', misScherm:'Something went wrong on this screen'
},
es:{
  loc:'es-ES', naam:'Español',
  'nav.vandaag':'Hoy', 'nav.aanvullen':'Reponer', 'nav.containers':'Contenedores', 'nav.labels':'Etiquetas de palé',
  'sync.laden':'cargando…', 'sync.ok':'conectado', 'sync.fout':'sin conexión', vernieuw:'Actualizar',
  week:'Semana {n}',
  lijstVan:'Backorders: {b} · Consejo de reposición: {a}',
  oud:'La lista no es de hoy. Actualízala primero.', oudKnop:'Actualizar lista →',
  'tegel.nu':'Mover ahora', ordersWacht:'{n} pedido esperando|{n} pedidos esperando',
  'tegel.ronde':'Ronda de reposición', 'tegel.rondeSub':'pendientes, por pasillo',
  'tegel.cont':'Contenedores', volgende:'Siguiente: {x}', geenGepland:'ninguno previsto',
  'tegel.labels':'Etiquetas de palé', 'tegel.labelsSub':'crear e imprimir etiquetas',
  uitlegTitel:'Cómo funciona la reposición',
  uitleg:[
    '<b>Actualizar la lista</b> (cada mañana y después de cada ronda): haz estas dos exportaciones en Picqer y arrástralas a la casilla <i>Actualizar lista</i>. La lista se actualiza para todos.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Mover ahora</b> primero. Aquí esperan pedidos de clientes. El pedido más antiguo está arriba. Coge la cantidad de la ubicación bulk (izquierda) y ponla en la ubicación pick (derecha).',
    '¿Pone <b>sin ubicación específica</b>? Entonces el producto no tiene ubicación pick: en Picqer, muévelo a "geen specifieke locatie".',
    'Registra también cada movimiento en Picqer (de bulk a pick) y marca aquí la casilla ✓. Así todos ven que está hecho.',
    '¿Todo lo de Mover ahora hecho? Picqer → Backorders → <b>Verwerk backorders</b> (procesar backorders). Los pedidos pasan a ser listas de picking.',
    'Después la <b>Ronda de reposición</b>: por pasillo, repón las ubicaciones pick con la cantidad del consejo. Regístralo también en Picqer y márcalo.',
    '¿Algo no cuadra (bulk vacío, otra cantidad, sitio equivocado)? Díselo a Daan.'
  ],
  vernieuwTitel:'Actualizar lista',
  dropTekst:'Arrastra aquí la exportación de backorders (Excel) y el consejo de reposición (PDF), o toca para elegir',
  bezig:'Procesando: {x}…', okBo:'✓ Backorders: {n} pedidos', okAdv:'✓ Consejo de reposición: {n} líneas',
  nietNodig:'✗ {x}: este archivo no hace falta aquí. Solo backorders (Excel) y consejo de reposición (PDF).',
  bijgewerkt:'Lista actualizada',
  open:'{n} pendientes', print:'Imprimir', gang:'Pasillo', alle:'todos', sinds:'desde {x}',
  orders:'{n} pedido|{n} pedidos', pickvrd:'stock en pick {n}', pqAdv:'consejo Picqer {n}',
  voorOrders:'para pedidos', advies:'consejo',
  geenLoc:'sin ubicación específica', ofNieuw:'o nueva:', bulkOnb:'bulk desconocido', geenPick:'sin ubicación pick',
  retourkar:'en carro de devoluciones {x}', wachtVst:'espera a VST: mover aún no completa ningún pedido',
  leegNu:'Nada que mover para pedidos.', leegRonde:'No hay ronda de reposición. Actualiza la lista con un nuevo consejo de reposición.',
  klaarNu:'¿Todo movido y registrado en Picqer? Entonces: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Hay pedidos de clientes esperando estos productos. El más antiguo arriba. De bulk (izquierda) a pick (derecha).',
  introRonde:'Resto del consejo de reposición, por pasillo en orden de recorrido. Repón la ubicación pick con la cantidad del consejo.',
  openVan:'{a} pendientes de {b}', nietIngeladen:'aún no cargado', vandaagOm:'hoy {x}',
  contIntro:'Contenedores que están por llegar. El plan de descarga (PDF) aparece en cuanto Daan lo haya completado todo.',
  eta:'ETA (estimada)', lossen:'Descarga', geenDatum:'aún sin fecha',
  pakbon:'Albarán', losplanning:'Plan de descarga (PDF)', losplanningVolgt:'Plan de descarga pendiente', gemaakt:'creado {x}',
  geenCont:'No hay contenedores previstos.',
  'st.concept':'en preparación', 'st.ingepland':'programado', 'st.gelost':'descargado',
  vandaag:'hoy', morgen:'mañana',
  openMislukt:'No se pudo abrir: {x}', bestandLaden:'Cargando archivo…',
  geenVerb:'Sin conexión con la base de datos', geenVerbTekst:'Vuelve a intentarlo en unos minutos. ¿Sigue igual? Díselo a Daan.',
  opgeslagen:'Guardado', misScherm:'Algo salió mal en esta pantalla'
},
el:{
  loc:'el-GR', naam:'Ελληνικά',
  'nav.vandaag':'Σήμερα', 'nav.aanvullen':'Αναπλήρωση', 'nav.containers':'Κοντέινερ', 'nav.labels':'Ετικέτες παλετών',
  'sync.laden':'φόρτωση…', 'sync.ok':'συνδέθηκε', 'sync.fout':'χωρίς σύνδεση', vernieuw:'Ανανέωση',
  week:'Εβδομάδα {n}',
  lijstVan:'Backorders: {b} · Πρόταση αναπλήρωσης: {a}',
  oud:'Η λίστα δεν είναι σημερινή. Ανανέωσέ την πρώτα.', oudKnop:'Ανανέωση λίστας →',
  'tegel.nu':'Μετακίνηση τώρα', ordersWacht:'{n} παραγγελία περιμένει|{n} παραγγελίες περιμένουν',
  'tegel.ronde':'Γύρος αναπλήρωσης', 'tegel.rondeSub':'ανοιχτά, ανά διάδρομο',
  'tegel.cont':'Κοντέινερ', volgende:'Επόμενο: {x}', geenGepland:'κανένα προγραμματισμένο',
  'tegel.labels':'Ετικέτες παλετών', 'tegel.labelsSub':'δημιουργία και εκτύπωση ετικετών',
  uitlegTitel:'Πώς γίνεται η αναπλήρωση',
  uitleg:[
    '<b>Ανανέωση λίστας</b> (κάθε πρωί και μετά από κάθε γύρο): κάνε αυτές τις δύο εξαγωγές στο Picqer και σύρε τις στο πλαίσιο <i>Ανανέωση λίστας</i>. Η λίστα ενημερώνεται για όλους.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b> (picklijst bulklocaties)',
    '<b>Μετακίνηση τώρα</b> πρώτα. Εδώ περιμένουν παραγγελίες πελατών. Η παλαιότερη παραγγελία είναι πάνω. Πάρε την ποσότητα από τη θέση bulk (αριστερά) και βάλ’ την στη θέση pick (δεξιά).',
    'Γράφει <b>χωρίς συγκεκριμένη θέση</b>; Τότε το προϊόν δεν έχει θέση pick: στο Picqer μετακίνησέ το σε «geen specifieke locatie».',
    'Κατάγραψε κάθε μετακίνηση και στο Picqer (από bulk σε pick) και πάτησε εδώ το κουτάκι ✓. Έτσι όλοι βλέπουν ότι έγινε.',
    'Έγιναν όλα στο «Μετακίνηση τώρα»; Picqer → Backorders → <b>Verwerk backorders</b> (επεξεργασία backorders). Οι παραγγελίες γίνονται λίστες συλλογής.',
    'Μετά ο <b>Γύρος αναπλήρωσης</b>: ανά διάδρομο, συμπλήρωσε τις θέσεις pick με την προτεινόμενη ποσότητα. Κατάγραψέ το και στο Picqer και σημείωσέ το.',
    'Κάτι δεν ταιριάζει (άδειο bulk, άλλη ποσότητα, λάθος θέση); Πες το στον Daan.'
  ],
  vernieuwTitel:'Ανανέωση λίστας',
  dropTekst:'Σύρε εδώ την εξαγωγή backorders (Excel) και την πρόταση αναπλήρωσης (PDF), ή πάτησε για επιλογή',
  bezig:'Επεξεργασία: {x}…', okBo:'✓ Backorders: {n} παραγγελίες', okAdv:'✓ Πρόταση αναπλήρωσης: {n} γραμμές',
  nietNodig:'✗ {x}: αυτό το αρχείο δεν χρειάζεται εδώ. Μόνο backorders (Excel) και πρόταση αναπλήρωσης (PDF).',
  bijgewerkt:'Η λίστα ενημερώθηκε',
  open:'{n} ανοιχτά', print:'Εκτύπωση', gang:'Διάδρομος', alle:'όλοι', sinds:'από {x}',
  orders:'{n} παραγγελία|{n} παραγγελίες', pickvrd:'απόθεμα pick {n}', pqAdv:'πρόταση Picqer {n}',
  voorOrders:'για παραγγελίες', advies:'πρόταση',
  geenLoc:'χωρίς συγκεκριμένη θέση', ofNieuw:'ή νέα:', bulkOnb:'άγνωστο bulk', geenPick:'χωρίς θέση pick',
  retourkar:'σε καρότσι επιστροφών {x}', wachtVst:'περιμένει VST: η μετακίνηση δεν ολοκληρώνει ακόμα παραγγελία',
  leegNu:'Τίποτα για μετακίνηση για παραγγελίες.', leegRonde:'Δεν υπάρχει γύρος αναπλήρωσης. Ανανέωσε τη λίστα με νέα πρόταση αναπλήρωσης.',
  klaarNu:'Όλα μετακινήθηκαν και καταγράφηκαν στο Picqer; Τότε: Picqer → Backorders → <b>Verwerk backorders</b>.',
  introNu:'Παραγγελίες πελατών περιμένουν αυτά τα προϊόντα. Η παλαιότερη πάνω. Από bulk (αριστερά) σε pick (δεξιά).',
  introRonde:'Υπόλοιπο της πρότασης αναπλήρωσης, ανά διάδρομο με σειρά διαδρομής. Συμπλήρωσε τη θέση pick με την προτεινόμενη ποσότητα.',
  openVan:'{a} ανοιχτά από {b}', nietIngeladen:'δεν έχει φορτωθεί ακόμα', vandaagOm:'σήμερα {x}',
  contIntro:'Κοντέινερ που έρχονται. Το πλάνο εκφόρτωσης (PDF) εμφανίζεται μόλις ο Daan συμπληρώσει τα πάντα.',
  eta:'ETA (εκτίμηση)', lossen:'Εκφόρτωση', geenDatum:'χωρίς ημερομηνία ακόμα',
  pakbon:'Δελτίο αποστολής', losplanning:'Πλάνο εκφόρτωσης (PDF)', losplanningVolgt:'Το πλάνο εκφόρτωσης ακολουθεί', gemaakt:'δημιουργήθηκε {x}',
  geenCont:'Δεν υπάρχουν προγραμματισμένα κοντέινερ.',
  'st.concept':'σε προετοιμασία', 'st.ingepland':'προγραμματισμένο', 'st.gelost':'ξεφορτώθηκε',
  vandaag:'σήμερα', morgen:'αύριο',
  openMislukt:'Δεν άνοιξε: {x}', bestandLaden:'Φόρτωση αρχείου…',
  geenVerb:'Χωρίς σύνδεση με τη βάση δεδομένων', geenVerbTekst:'Δοκίμασε ξανά σε λίγα λεπτά. Αν συνεχίζει, πες το στον Daan.',
  opgeslagen:'Αποθηκεύτηκε', misScherm:'Κάτι πήγε στραβά σε αυτή την οθόνη'
}
};

/* ---- testdag 30-9: prioriteit, "niet nu", barcode, papieren lijst, Verwerk backorders ---- */
Object.assign(window.JT.nl, {
  'nav.handleiding':'Handleiding', handTaal:'Kies bovenaan de taal: NL, EN, ES of EL.',
  meldKnop:'klopt niet / past niet', meldGedaan:'gemeld', meldUitleg:'Wat past er echt op de picklocatie? Daan ziet het en past het aanvulniveau aan.', meldMax:'Max op picklocatie', meldNoot:'Opmerking', meldVb:'bv. 2 dozen van 8, bulk leeg, andere plek', opslaan:'Opslaan', sluit:'Sluiten',
  kar:'Retourkar',
  pallets:'{n} pallet|{n} pallets',
  'tegel.niet':'Niet nu', 'tegel.nietSub':'Picqer-advies, maar de order is nog niet compleet',
  volg:'Volgorde', volgOud:'oudste order eerst', volgRoute:'looproute',
  van:'van', naar:'naar', verpl:'verplaatsen', oudste:'oudste {x}', voorOrd:'{n} voor orders', dz:'deelzending',
  nogOpen:'Afgevinkt om {a}, maar na Verwerk backorders ({b}) staat hij er nog. Echt verplaatst in Picqer? Genoeg verplaatst?',
  verwerkKnop:'Verwerk backorders gedaan', verwerkUit:'Toch niet', verwerkOm:'✓ Verwerk backorders gedaan om {x}',
  verwerkNa:'Daarna de backorder-export opnieuw inladen (vak bovenaan): wat er dan nog staat, wordt rood.',
  introNiet:'Picqer zegt verplaatsen, maar de order wordt er niet compleet van: het product is maar deels op voorraad, of de order wacht ook op iets anders. Niet verplaatsen. Spreekt Daan een deelzending af, dan komt het vanzelf bij Nu verplaatsen.',
  deelsEigen:'{nr}: {b} van {a} op voorraad (wacht op inkoop)', deelsAnder:'{nr}: wacht ook op {x}', deelsVst:'{nr}: de rest komt van VST',
  deelsKort:'order nog niet compleet', leegNiet:'Niets: geen advies voor orders die nog niet compleet zijn.',
  printOp:'afgedrukt {x}', kolProduct:'Product', kolVan:'Van (bulk)', kolNaar:'Naar (pick)', kolAantal:'Aantal', kolGedaan:'Gedaan',
  scanTip:'Picqer-app → Aanvuladvies: scan de barcode op deze lijst, het verplaatsvenster opent. Kies bij NAAR de picklocatie, niet een container (containers 1–6 zijn retourkarren).',
  diff:'Sinds de vorige lijst: {a} orders opgelost · {b} nog open · {c} nieuw',
  nietHerkend:'✗ {x}: niet herkend als backorder-export of aanvuladvies.',
  introNu:'Klantorders wachten op deze producten; verder is de order compleet. Oudste order bovenaan. Groot getal = hoeveel je verplaatst.',
  uitleg:[
    '<b>Lijst vernieuwen</b> (elke ochtend en na elke Verwerk backorders), op elke computer: maak in Picqer deze twee exports en sleep ze in het vak <i>Lijst vernieuwen</i>. De lijst wordt voor iedereen bijgewerkt.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b>',
    '<b>1 · Nu verplaatsen</b> eerst: hier wachten klantorders op, verder zijn ze compleet. Oudste order bovenaan. Print de lijst (knop Print) of werk op de telefoon.',
    '<b>Scannen</b>: open in de Picqer-app het Aanvuladvies en scan de barcode op de lijst; het verplaatsvenster opent. Kies bij <b>naar</b> de picklocatie (rechts op de lijst), niet een container: containers 1–6 zijn retourkarren. Staat er <b>geen specifieke locatie</b>? Dan daarheen, alleen het aantal voor de orders.',
    'Klopt de voorraad niet (bulk leeg, meer of minder op de picklocatie)? Pas het meteen aan in de scanner. Tik daarna het vakje hier aan ✓ en schrijf op papier het echte aantal bij <i>Gedaan</i>.',
    'Lijst klaar? Picqer → Backorders → <b>Verwerk backorders</b>, en tik hier <i>Verwerk backorders gedaan</i> aan. Vernieuw daarna de lijst: wat er dan nog staat, wordt rood.',
    'Daarna <b>2 · Aanvulronde</b>: per gang de picklocaties aanvullen met het aantal van het advies. Ook in Picqer verwerken en aftikken.',
    '<b>Niet nu</b>: Picqer adviseert het wel, maar de order wordt er niet compleet van. Niet verplaatsen, tenzij Daan een deelzending afspreekt. Iets raar? Meld het bij Daan.'
  ]
});
Object.assign(window.JT.en, {
  'nav.handleiding':'Manual', handTaal:'Choose the language at the top: NL, EN, ES or EL.',
  meldKnop:'not right / does not fit', meldGedaan:'reported', meldUitleg:'What really fits on the pick location? Daan sees it and adjusts the replenishment level.', meldMax:'Max on pick location', meldNoot:'Remark', meldVb:'e.g. 2 boxes of 8, bulk empty, other place', opslaan:'Save', sluit:'Close',
  kar:'Return cart',
  pallets:'{n} pallet|{n} pallets',
  'tegel.niet':'Not now', 'tegel.nietSub':'Picqer advice, but the order is not complete yet',
  volg:'Order', volgOud:'oldest order first', volgRoute:'walking route',
  van:'from', naar:'to', verpl:'move', oudste:'oldest {x}', voorOrd:'{n} for orders', dz:'partial shipment',
  nogOpen:'Ticked at {a}, but after Verwerk backorders ({b}) it is still here. Really moved in Picqer? Moved enough?',
  verwerkKnop:'Verwerk backorders done', verwerkUit:'Undo', verwerkOm:'✓ Verwerk backorders done at {x}',
  verwerkNa:'Then load the backorder export again (box at the top): anything still left turns red.',
  introNiet:'Picqer says move it, but moving it does not complete the order: the product is only partly in stock, or the order is also waiting for something else. Do not move. If Daan agrees a partial shipment, it appears in Move now by itself.',
  deelsEigen:'{nr}: {b} of {a} in stock (waiting for purchase)', deelsAnder:'{nr}: also waiting for {x}', deelsVst:'{nr}: the rest comes from VST',
  deelsKort:'order not complete yet', leegNiet:'Nothing: no advice for orders that are not complete yet.',
  printOp:'printed {x}', kolProduct:'Product', kolVan:'From (bulk)', kolNaar:'To (pick)', kolAantal:'Qty', kolGedaan:'Done',
  scanTip:'Picqer app → Aanvuladvies: scan the barcode on this list, the move screen opens. For TO choose the pick location, not a container (containers 1–6 are return carts).',
  diff:'Since the previous list: {a} orders solved · {b} still open · {c} new',
  nietHerkend:'✗ {x}: not recognised as a backorder export or replenishment advice.',
  introNu:'Customer orders are waiting for these products; otherwise the order is complete. Oldest order at the top. Big number = how many to move.',
  uitleg:[
    '<b>Refresh the list</b> (every morning and after every Verwerk backorders), on any computer: make these two exports in Picqer and drop them in the box <i>Refresh list</i>. The list updates for everyone.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b>',
    '<b>1 · Move now</b> first: customer orders are waiting for these, otherwise they are complete. Oldest order at the top. Print the list (Print button) or work on your phone.',
    '<b>Scanning</b>: in the Picqer app open Aanvuladvies and scan the barcode on the list; the move screen opens. For <b>to</b> choose the pick location (right on the list), not a container: containers 1–6 are return carts. Does it say <b>no specific location</b>? Move it there, only the quantity for the orders.',
    'Stock not right (bulk empty, more or less on the pick location)? Correct it straight away in the scanner. Then tick the box here ✓ and write the real quantity under <i>Done</i> on paper.',
    'List done? Picqer → Backorders → <b>Verwerk backorders</b>, and tick <i>Verwerk backorders done</i> here. Then refresh the list: anything still left turns red.',
    'Then <b>2 · Replenishment round</b>: per aisle, top up the pick locations with the advised quantity. Also process it in Picqer and tick it off.',
    '<b>Not now</b>: Picqer advises it, but it does not complete the order. Do not move, unless Daan agrees a partial shipment. Something odd? Tell Daan.'
  ]
});
Object.assign(window.JT.es, {
  'nav.handleiding':'Manual', handTaal:'Elige el idioma arriba: NL, EN, ES o EL.',
  meldKnop:'no cuadra / no cabe', meldGedaan:'avisado', meldUitleg:'¿Cuánto cabe de verdad en la ubicación pick? Daan lo ve y ajusta el nivel de reposición.', meldMax:'Máx. en ubicación pick', meldNoot:'Comentario', meldVb:'p. ej. 2 cajas de 8, bulk vacío, otro sitio', opslaan:'Guardar', sluit:'Cerrar',
  kar:'Carro devoluciones',
  pallets:'{n} palé|{n} palés',
  'tegel.niet':'Ahora no', 'tegel.nietSub':'consejo de Picqer, pero el pedido aún no está completo',
  volg:'Orden', volgOud:'pedido más antiguo primero', volgRoute:'recorrido',
  van:'de', naar:'a', verpl:'mover', oudste:'más antiguo {x}', voorOrd:'{n} para pedidos', dz:'envío parcial',
  nogOpen:'Marcado a las {a}, pero después de Verwerk backorders ({b}) sigue aquí. ¿Movido de verdad en Picqer? ¿Suficiente?',
  verwerkKnop:'Verwerk backorders hecho', verwerkUit:'Deshacer', verwerkOm:'✓ Verwerk backorders hecho a las {x}',
  verwerkNa:'Después vuelve a cargar la exportación de backorders (casilla de arriba): lo que siga aquí se pone en rojo.',
  introNiet:'Picqer dice mover, pero moverlo no completa el pedido: el producto solo está en parte en stock, o el pedido también espera otra cosa. No lo muevas. Si Daan acuerda un envío parcial, aparece solo en Mover ahora.',
  deelsEigen:'{nr}: {b} de {a} en stock (espera compra)', deelsAnder:'{nr}: también espera {x}', deelsVst:'{nr}: el resto viene de VST',
  deelsKort:'pedido aún no completo', leegNiet:'Nada: no hay consejo para pedidos que aún no están completos.',
  printOp:'impreso {x}', kolProduct:'Producto', kolVan:'De (bulk)', kolNaar:'A (pick)', kolAantal:'Cant.', kolGedaan:'Hecho',
  scanTip:'App de Picqer → Aanvuladvies: escanea el código de barras de esta lista y se abre la pantalla de mover. En A elige la ubicación pick, no un contenedor (los contenedores 1–6 son carros de devoluciones).',
  diff:'Desde la lista anterior: {a} pedidos resueltos · {b} aún abiertos · {c} nuevos',
  nietHerkend:'✗ {x}: no se reconoce como exportación de backorders ni consejo de reposición.',
  introNu:'Hay pedidos de clientes esperando estos productos; por lo demás el pedido está completo. El más antiguo arriba. Número grande = cuánto mover.',
  uitleg:[
    '<b>Actualizar la lista</b> (cada mañana y después de cada Verwerk backorders), en cualquier ordenador: haz estas dos exportaciones en Picqer y arrástralas a la casilla <i>Actualizar lista</i>. La lista se actualiza para todos.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b>',
    '<b>1 · Mover ahora</b> primero: aquí esperan pedidos de clientes, por lo demás están completos. El más antiguo arriba. Imprime la lista (botón Imprimir) o trabaja con el móvil.',
    '<b>Escanear</b>: en la app de Picqer abre Aanvuladvies y escanea el código de barras de la lista; se abre la pantalla de mover. En <b>a</b> elige la ubicación pick (a la derecha en la lista), no un contenedor: los contenedores 1–6 son carros de devoluciones. ¿Pone <b>sin ubicación específica</b>? Muévelo ahí, solo la cantidad para los pedidos.',
    '¿El stock no cuadra (bulk vacío, más o menos en la ubicación pick)? Corrígelo enseguida en el escáner. Luego marca la casilla aquí ✓ y escribe en el papel la cantidad real en <i>Hecho</i>.',
    '¿Lista terminada? Picqer → Backorders → <b>Verwerk backorders</b>, y marca aquí <i>Verwerk backorders hecho</i>. Después actualiza la lista: lo que siga ahí se pone en rojo.',
    'Después la <b>2 · Ronda de reposición</b>: por pasillo, repón las ubicaciones pick con la cantidad del consejo. Regístralo también en Picqer y márcalo.',
    '<b>Ahora no</b>: Picqer lo aconseja, pero no completa el pedido. No lo muevas, salvo que Daan acuerde un envío parcial. ¿Algo raro? Díselo a Daan.'
  ]
});
Object.assign(window.JT.el, {
  'nav.handleiding':'Εγχειρίδιο', handTaal:'Διάλεξε τη γλώσσα πάνω: NL, EN, ES ή EL.',
  meldKnop:'δεν ταιριάζει / δεν χωράει', meldGedaan:'δηλώθηκε', meldUitleg:'Πόσα χωράνε πραγματικά στη θέση pick; Ο Daan το βλέπει και προσαρμόζει το επίπεδο αναπλήρωσης.', meldMax:'Μέγ. στη θέση pick', meldNoot:'Σχόλιο', meldVb:'π.χ. 2 κούτες των 8, άδειο bulk, άλλη θέση', opslaan:'Αποθήκευση', sluit:'Κλείσιμο',
  kar:'Καρότσι επιστροφών',
  pallets:'{n} παλέτα|{n} παλέτες',
  'tegel.niet':'Όχι τώρα', 'tegel.nietSub':'πρόταση Picqer, αλλά η παραγγελία δεν είναι ακόμα πλήρης',
  volg:'Σειρά', volgOud:'παλαιότερη παραγγελία πρώτα', volgRoute:'διαδρομή',
  van:'από', naar:'προς', verpl:'μετακίνηση', oudste:'παλαιότερη {x}', voorOrd:'{n} για παραγγελίες', dz:'μερική αποστολή',
  nogOpen:'Σημειώθηκε στις {a}, αλλά μετά το Verwerk backorders ({b}) είναι ακόμα εδώ. Μετακινήθηκε πραγματικά στο Picqer; Αρκετό;',
  verwerkKnop:'Verwerk backorders έγινε', verwerkUit:'Αναίρεση', verwerkOm:'✓ Verwerk backorders έγινε στις {x}',
  verwerkNa:'Μετά φόρτωσε ξανά την εξαγωγή backorders (πλαίσιο πάνω): ό,τι μένει γίνεται κόκκινο.',
  introNiet:'Το Picqer λέει μετακίνηση, αλλά αυτό δεν ολοκληρώνει την παραγγελία: το προϊόν υπάρχει μόνο εν μέρει, ή η παραγγελία περιμένει και κάτι άλλο. Μην το μετακινείς. Αν ο Daan συμφωνήσει μερική αποστολή, εμφανίζεται μόνο του στο «Μετακίνηση τώρα».',
  deelsEigen:'{nr}: {b} από {a} σε απόθεμα (περιμένει αγορά)', deelsAnder:'{nr}: περιμένει και {x}', deelsVst:'{nr}: το υπόλοιπο έρχεται από VST',
  deelsKort:'η παραγγελία δεν είναι ακόμα πλήρης', leegNiet:'Τίποτα: καμία πρόταση για παραγγελίες που δεν είναι ακόμα πλήρεις.',
  printOp:'εκτυπώθηκε {x}', kolProduct:'Προϊόν', kolVan:'Από (bulk)', kolNaar:'Προς (pick)', kolAantal:'Ποσ.', kolGedaan:'Έγινε',
  scanTip:'Εφαρμογή Picqer → Aanvuladvies: σκάναρε το barcode σε αυτή τη λίστα, ανοίγει η οθόνη μετακίνησης. Στο ΠΡΟΣ διάλεξε τη θέση pick, όχι κοντέινερ (τα κοντέινερ 1–6 είναι καρότσια επιστροφών).',
  diff:'Από την προηγούμενη λίστα: {a} παραγγελίες λύθηκαν · {b} ακόμα ανοιχτές · {c} νέες',
  nietHerkend:'✗ {x}: δεν αναγνωρίστηκε ως εξαγωγή backorders ή πρόταση αναπλήρωσης.',
  introNu:'Παραγγελίες πελατών περιμένουν αυτά τα προϊόντα· κατά τα άλλα η παραγγελία είναι πλήρης. Η παλαιότερη πάνω. Μεγάλος αριθμός = πόσα μετακινείς.',
  uitleg:[
    '<b>Ανανέωση λίστας</b> (κάθε πρωί και μετά από κάθε Verwerk backorders), σε οποιονδήποτε υπολογιστή: κάνε αυτές τις δύο εξαγωγές στο Picqer και σύρε τις στο πλαίσιο <i>Ανανέωση λίστας</i>. Η λίστα ενημερώνεται για όλους.<br>• Picqer → Backorders → <b>Exporteer backorders</b> (Excel)<br>• Picqer → Aanvuladvies → <b>PDF</b>',
    '<b>1 · Μετακίνηση τώρα</b> πρώτα: εδώ περιμένουν παραγγελίες πελατών, κατά τα άλλα πλήρεις. Η παλαιότερη πάνω. Τύπωσε τη λίστα (κουμπί Εκτύπωση) ή δούλεψε στο κινητό.',
    '<b>Σκανάρισμα</b>: στην εφαρμογή Picqer άνοιξε το Aanvuladvies και σκάναρε το barcode της λίστας· ανοίγει η οθόνη μετακίνησης. Στο <b>προς</b> διάλεξε τη θέση pick (δεξιά στη λίστα), όχι κοντέινερ: τα κοντέινερ 1–6 είναι καρότσια επιστροφών. Γράφει <b>χωρίς συγκεκριμένη θέση</b>; Μετακίνησέ το εκεί, μόνο την ποσότητα για τις παραγγελίες.',
    'Δεν ταιριάζει το απόθεμα (άδειο bulk, περισσότερα ή λιγότερα στη θέση pick); Διόρθωσέ το αμέσως στο σκάνερ. Μετά πάτησε το κουτάκι εδώ ✓ και γράψε στο χαρτί την πραγματική ποσότητα στο <i>Έγινε</i>.',
    'Τελείωσε η λίστα; Picqer → Backorders → <b>Verwerk backorders</b>, και πάτησε εδώ <i>Verwerk backorders έγινε</i>. Μετά ανανέωσε τη λίστα: ό,τι μένει γίνεται κόκκινο.',
    'Μετά ο <b>2 · Γύρος αναπλήρωσης</b>: ανά διάδρομο, συμπλήρωσε τις θέσεις pick με την προτεινόμενη ποσότητα. Κατάγραψέ το και στο Picqer και σημείωσέ το.',
    '<b>Όχι τώρα</b>: το Picqer το προτείνει, αλλά δεν ολοκληρώνει την παραγγελία. Μην το μετακινείς, εκτός αν ο Daan συμφωνήσει μερική αποστολή. Κάτι περίεργο; Πες το στον Daan.'
  ]
});

/* ---- 7-10: Nu verplaatsen live uit Picqer ---- */
Object.assign(window.JT.nl, { live:'Nu verplaatsen: live uit Picqer ({x})', 'live.titel':'Picqer koppelen', 'live.uitleg':'Vul één keer de koppelcode in (vraag Daan). Daarna komt Nu verplaatsen live uit Picqer, zonder exports.', 'live.knop':'Koppelen', 'live.fout':'Picqer is nu niet bereikbaar: Nu verplaatsen komt uit de laatste export.' });
Object.assign(window.JT.en, { live:'Move now: live from Picqer ({x})', 'live.titel':'Connect Picqer', 'live.uitleg':'Enter the link code once (ask Daan). After that, Move now comes live from Picqer, without exports.', 'live.knop':'Connect', 'live.fout':'Picqer cannot be reached right now: Move now uses the last export.' });
Object.assign(window.JT.es, { live:'Mover ahora: en vivo de Picqer ({x})', 'live.titel':'Conectar Picqer', 'live.uitleg':'Introduce una vez el código de enlace (pregunta a Daan). Después, Mover ahora llega en vivo de Picqer, sin exportaciones.', 'live.knop':'Conectar', 'live.fout':'Picqer no está disponible ahora: Mover ahora usa la última exportación.' });
Object.assign(window.JT.el, { live:'Μετακίνηση τώρα: ζωντανά από Picqer ({x})', 'live.titel':'Σύνδεση Picqer', 'live.uitleg':'Βάλτε μία φορά τον κωδικό σύνδεσης (ρωτήστε τον Daan). Μετά η Μετακίνηση τώρα έρχεται ζωντανά από το Picqer, χωρίς εξαγωγές.', 'live.knop':'Σύνδεση', 'live.fout':'Το Picqer δεν είναι διαθέσιμο τώρα: η Μετακίνηση τώρα χρησιμοποιεί την τελευταία εξαγωγή.' });

/* ---- 7-10: overzicht picklijsten en backorders (live) ---- */
Object.assign(window.JT.en, {
  'lv.picklijsten':'Picklists', 'lv.tikTegel':'tap a tile for the list', 'lv.oudsteOpen':'oldest open {x}',
  'lv.open':'Open', 'lv.urgent':'Urgent', 'lv.o24':'Older than 24 hours', 'lv.o12':'Older than 12 hours', 'lv.o4':'Older than 4 hours',
  'lv.pauze':'Paused', 'lv.pauzeSub':'with reason', 'lv.snooze':'Snoozed', 'lv.snoozeSub':'until a date',
  'lv.backorders':'Backorders', 'lv.boAlle':'Orders in backorder', 'lv.regels':'{n} line|{n} lines', 'lv.boVol':'All in stock', 'lv.boVolSub':'only move or process',
  'lv.boProd':'Products', 'lv.boProdSub':'for those orders', 'lv.boWacht':'Waiting for stock', 'lv.boWachtSub':'not everything in stock',
  'lv.tl.open':'Open picklists', 'lv.tl.urgent':'Urgent picklists', 'lv.tl.o24':'Open, older than 24 hours', 'lv.tl.o12':'Open, older than 12 hours', 'lv.tl.o4':'Open, older than 4 hours',
  'lv.tl.pauze':'Paused picklists', 'lv.tl.snooze':'Snoozed picklists', 'lv.tl.bo-alle':'Orders in backorder', 'lv.tl.bo-vol':'Orders with everything in stock', 'lv.tl.bo-wacht':'Orders waiting for stock',
  'lv.kPicklijst':'Picklist', 'lv.kAangemaakt':'Created', 'lv.kProducten':'Products', 'lv.kReden':'Pause reason', 'lv.kTot':'Snoozed until', 'lv.kToegewezen':'Assigned', 'lv.kRef':'Reference',
  'lv.kOrder':'Order', 'lv.kSinds':'In backorder since', 'lv.kRegels':'Lines', 'lv.kOpVoorraad':'In stock',
  'lv.opm':'comments', 'lv.verberg':'hide', 'lv.sluiten':'close', 'lv.ophalen':'Loading comments…', 'lv.geenOpm':'No comments.', 'lv.klant':'Customer remark', 'lv.opmerking':'Comment',
  'lv.gepickt':'{n} picked', 'lv.voorkeur':'preferred {x}', 'lv.alles':'all', 'lv.vanTot':'{a} of {b}', 'lv.opVrd':'({n} in stock)', 'lv.geenPl':'No picklists.', 'lv.geenOrders':'No orders.',
  'lv.codeNoot':'Product codes are shown for orders with everything in stock; for the others only the Picqer number.', 'lv.ja':'yes', 'lv.order':'order {x}',
  'lv.min':'{n} min', 'lv.uur':'{n} h', 'lv.dagen':'{n} days'
});
Object.assign(window.JT.es, {
  'lv.picklijsten':'Listas de picking', 'lv.tikTegel':'toca una casilla para ver la lista', 'lv.oudsteOpen':'la más antigua abierta {x}',
  'lv.open':'Abiertas', 'lv.urgent':'Urgente', 'lv.o24':'Más de 24 horas', 'lv.o12':'Más de 12 horas', 'lv.o4':'Más de 4 horas',
  'lv.pauze':'En pausa', 'lv.pauzeSub':'con motivo', 'lv.snooze':'Pospuestas', 'lv.snoozeSub':'hasta una fecha',
  'lv.backorders':'Backorders', 'lv.boAlle':'Pedidos en backorder', 'lv.regels':'{n} línea|{n} líneas', 'lv.boVol':'Todo en stock', 'lv.boVolSub':'solo mover o procesar',
  'lv.boProd':'Productos', 'lv.boProdSub':'para esos pedidos', 'lv.boWacht':'Esperando stock', 'lv.boWachtSub':'no todo en stock',
  'lv.tl.open':'Listas de picking abiertas', 'lv.tl.urgent':'Listas de picking urgentes', 'lv.tl.o24':'Abiertas, más de 24 horas', 'lv.tl.o12':'Abiertas, más de 12 horas', 'lv.tl.o4':'Abiertas, más de 4 horas',
  'lv.tl.pauze':'Listas de picking en pausa', 'lv.tl.snooze':'Listas de picking pospuestas', 'lv.tl.bo-alle':'Pedidos en backorder', 'lv.tl.bo-vol':'Pedidos con todo en stock', 'lv.tl.bo-wacht':'Pedidos esperando stock',
  'lv.kPicklijst':'Lista', 'lv.kAangemaakt':'Creada', 'lv.kProducten':'Productos', 'lv.kReden':'Motivo de pausa', 'lv.kTot':'Pospuesta hasta', 'lv.kToegewezen':'Asignada', 'lv.kRef':'Referencia',
  'lv.kOrder':'Pedido', 'lv.kSinds':'En backorder desde', 'lv.kRegels':'Líneas', 'lv.kOpVoorraad':'En stock',
  'lv.opm':'comentarios', 'lv.verberg':'ocultar', 'lv.sluiten':'cerrar', 'lv.ophalen':'Cargando comentarios…', 'lv.geenOpm':'Sin comentarios.', 'lv.klant':'Comentario del cliente', 'lv.opmerking':'Comentario',
  'lv.gepickt':'{n} recogidos', 'lv.voorkeur':'preferencia {x}', 'lv.alles':'todo', 'lv.vanTot':'{a} de {b}', 'lv.opVrd':'({n} en stock)', 'lv.geenPl':'No hay listas.', 'lv.geenOrders':'No hay pedidos.',
  'lv.codeNoot':'Los códigos de producto aparecen en los pedidos con todo en stock; en los demás solo el número de Picqer.', 'lv.ja':'sí', 'lv.order':'pedido {x}',
  'lv.min':'{n} min', 'lv.uur':'{n} h', 'lv.dagen':'{n} días'
});
Object.assign(window.JT.el, {
  'lv.picklijsten':'Λίστες συλλογής', 'lv.tikTegel':'πατήστε ένα πλακίδιο για τη λίστα', 'lv.oudsteOpen':'η παλαιότερη ανοιχτή {x}',
  'lv.open':'Ανοιχτές', 'lv.urgent':'Επείγουσες', 'lv.o24':'Πάνω από 24 ώρες', 'lv.o12':'Πάνω από 12 ώρες', 'lv.o4':'Πάνω από 4 ώρες',
  'lv.pauze':'Σε παύση', 'lv.pauzeSub':'με αιτία', 'lv.snooze':'Σε αναβολή', 'lv.snoozeSub':'έως μια ημερομηνία',
  'lv.backorders':'Backorders', 'lv.boAlle':'Παραγγελίες σε backorder', 'lv.regels':'{n} γραμμή|{n} γραμμές', 'lv.boVol':'Όλα σε απόθεμα', 'lv.boVolSub':'μόνο μετακίνηση ή επεξεργασία',
  'lv.boProd':'Προϊόντα', 'lv.boProdSub':'για αυτές τις παραγγελίες', 'lv.boWacht':'Περιμένουν απόθεμα', 'lv.boWachtSub':'όχι όλα σε απόθεμα',
  'lv.tl.open':'Ανοιχτές λίστες', 'lv.tl.urgent':'Επείγουσες λίστες', 'lv.tl.o24':'Ανοιχτές, πάνω από 24 ώρες', 'lv.tl.o12':'Ανοιχτές, πάνω από 12 ώρες', 'lv.tl.o4':'Ανοιχτές, πάνω από 4 ώρες',
  'lv.tl.pauze':'Λίστες σε παύση', 'lv.tl.snooze':'Λίστες σε αναβολή', 'lv.tl.bo-alle':'Παραγγελίες σε backorder', 'lv.tl.bo-vol':'Παραγγελίες με όλα σε απόθεμα', 'lv.tl.bo-wacht':'Παραγγελίες που περιμένουν απόθεμα',
  'lv.kPicklijst':'Λίστα', 'lv.kAangemaakt':'Δημιουργήθηκε', 'lv.kProducten':'Προϊόντα', 'lv.kReden':'Αιτία παύσης', 'lv.kTot':'Αναβολή έως', 'lv.kToegewezen':'Ανατέθηκε', 'lv.kRef':'Αναφορά',
  'lv.kOrder':'Παραγγελία', 'lv.kSinds':'Σε backorder από', 'lv.kRegels':'Γραμμές', 'lv.kOpVoorraad':'Σε απόθεμα',
  'lv.opm':'σχόλια', 'lv.verberg':'απόκρυψη', 'lv.sluiten':'κλείσιμο', 'lv.ophalen':'Φόρτωση σχολίων…', 'lv.geenOpm':'Χωρίς σχόλια.', 'lv.klant':'Σχόλιο πελάτη', 'lv.opmerking':'Σχόλιο',
  'lv.gepickt':'{n} συλλέχθηκαν', 'lv.voorkeur':'προτίμηση {x}', 'lv.alles':'όλα', 'lv.vanTot':'{a} από {b}', 'lv.opVrd':'({n} σε απόθεμα)', 'lv.geenPl':'Δεν υπάρχουν λίστες.', 'lv.geenOrders':'Δεν υπάρχουν παραγγελίες.',
  'lv.codeNoot':'Οι κωδικοί προϊόντων φαίνονται στις παραγγελίες με όλα σε απόθεμα· στις υπόλοιπες μόνο ο αριθμός Picqer.', 'lv.ja':'ναι', 'lv.order':'παραγγελία {x}',
  'lv.min':'{n} λεπτά', 'lv.uur':'{n} ώρες', 'lv.dagen':'{n} ημέρες'
});

/* ---- 7-10: aanvullen live, Vernieuwen in plaats van afvinken ---- */
Object.assign(window.JT.nl, { liveTip:'Verplaats in de Picqer-app en tik daarna op Vernieuwen: wat klaar is, verdwijnt van de lijst.', gedaan:'Vandaag al gedaan ({n})', rondeLive:'Aanvulronde: Picqer {x}', bezigLive:'bijwerken…', rondeNog:'De aanvulronde komt nog uit de PDF van het aanvuladvies.' });
Object.assign(window.JT.en, { liveTip:'Move it in the Picqer app, then tap Refresh: what is done disappears from the list.', gedaan:'Already done today ({n})', rondeLive:'Replenishment round: Picqer {x}', bezigLive:'updating…', rondeNog:'The replenishment round still comes from the replenishment advice PDF.' });
Object.assign(window.JT.es, { liveTip:'Muévelo en la app de Picqer y luego toca Actualizar: lo que está hecho desaparece de la lista.', gedaan:'Ya hecho hoy ({n})', rondeLive:'Ronda de reposición: Picqer {x}', bezigLive:'actualizando…', rondeNog:'La ronda de reposición todavía viene del PDF del consejo de reposición.' });
Object.assign(window.JT.el, { liveTip:'Μετακινήστε στην εφαρμογή Picqer και μετά πατήστε Ανανέωση: ό,τι έγινε φεύγει από τη λίστα.', gedaan:'Έγινε ήδη σήμερα ({n})', rondeLive:'Γύρος αναπλήρωσης: Picqer {x}', bezigLive:'ενημέρωση…', rondeNog:'Ο γύρος αναπλήρωσης έρχεται ακόμα από το PDF της πρότασης αναπλήρωσης.' });
